name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Yarn
        run: npm install -g yarn
      - name: Remove git config
        run: |
          git config --local --unset http.https://github.com/.extraheader
      - name: Remove package-lock.json
        run: rm package-lock.json
      - name: Install Dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Build
        run: yarn build --no-warnings
        env:
          CI: true
      - name: Deploy
        run: yarn run azure-static-web-apps-preview --token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        env:
          AzureStaticWebAppsApiToken: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          ApiLocation: "" # API source code path - optional
          AppLocation: "/" # App source code path
          OutputLocation: "build" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        run: yarn run azure-static-web-apps-preview --token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} --close-pr
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        env:
          AzureStaticWebAppsApiToken: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        ###### End of Repository/Build Configurations ######
