name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn add --dev @babel/plugin-proposal-private-property-in-object
          yarn build
      - name: Serve
        run: |
          yarn global add serve
          serve -s build &
      - name: Start PM2
        run: |
          yarn global add pm2
          pm2 start serve --name "my-app" --no-autorestart --silent
      - name: Deploy App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_FIELD_090D2CA00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # App source code path
          api_location: "/api" # Update this path to your API source code path
          output_location: "build" # Built app content directory - optional

  deploy_api_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Deploy API Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Update React version for @brainhubeu/react-carousel
        run: yarn add @brainhubeu/react-carousel@2.0.4 react@18.2.0
      - name: Deploy API
        id: deployapi
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_FIELD_090D2CA00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # App source code path
          api_location: "/api" # Update this path to your API source code path

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_FIELD_090D2CA00 }}
          action: "close"
